### PR TITLE
#17: fixed all allowed type checking

### PR DESCRIPTION
**Pull request by fkrafi**

### CODE REVIEW

**Review by iluxa86 — APPROVED** [review]

**Comment by fkrafi** [comment]
@mitsha-microsoft can you please review this PR

**Comment by mitsha-microsoft** [comment]
LGTM. Adding current owners @anraghun @romil07 @anukgupt to look into this & complete it. Also #35 (though a tad bit incomplete) does the same.

**Comment by fkrafi** [comment]
@anraghun, @romil07 , @anukgupt , can you please review this PR.

**Comment by fkrafi** [comment]
is this project dead?

**Comment by kanika1894** [comment]
Thanks for your contribution.
There seem to be duplicate PRs. 
Will be taking this https://github.com/Azure/aci-deploy/pull/43 forward.
Hope it works.

**Pull request closed without merging**
