### PR TITLE
Fix some of the parameter validations for fields that require specific

### PR DESCRIPTION
**Pull request by mauricioborges**

### CODE REVIEW

**Comment by mauricioborges** [comment]
@mitsha-microsoft would you mind taking a look?

**Comment by mitsha-microsoft** [comment]
@mauricioborges LGTM, but I dont have permissions to close this PR. Tagging @anraghun @narula0781 who can close this PR

**Comment by fkrafi** [comment]
i have already created a PR for this issue, https://github.com/Azure/aci-deploy/pull/25 which has been hanging since Oct 31, 2020.

**Comment by mauricioborges** [comment]
It's true @fkrafi. Any chance we can have external contributors to this project? I'll be more than happy to start contributing as an admin to merge these PR. @mitsha-microsoft if you have any idea on how to do that, I would appreciate your help :)

**Review by kanika1894 — APPROVED** [review]
Thanks for contributing @mauricioborges

**Pull request merged**
