### PR TITLE
Environment-variables and secure-environment-variables now parsed according to action.yml

### PR DESCRIPTION
**Pull request by andrioid**
## Motivation for this change

I've spent 2 days trying to get my Container Instance to talk to a Postgres server where I have to pass a PG connection string. I was unsure if the problem was with Github secrets, Github actions, This action or with the Azure API.

The connection string is defined in the format of `PG_DSN=postgres://user:pass@hostname/dbname?sslmode=require` or `PG_DSN=host=hostname user=myuser password=mypassword`

Both of these strings cause issues for the naive `string.split(' ')` and `string.split('=')` approach used currently.

> 'List of secure environment variables for the container. Space seperated values in "key=value" format'

The `action.yml` says that if you use spaces, you should add quotes, but I can't see that these quotes are handled anywhere.

## Changes

- I've added  `parseForPairs()` and `parsePair()` utility functions and changed how the environment variables are parsed.

## Comments

I just hope this will help the next person trying to use database connection strings with this action. Please give it a read and see if this can be used.

### CODE REVIEW

**Comment by IslamHeggy** [comment]
I have been trying to assign some environment variables to connection strings and it keeps not parsing the = and ends up failing. 

I think we need this fix, Otherwise I will be using the az client instead of using limited action.

**Comment by mitsha-microsoft** [comment]
I think #14 fixes your issue

**Comment by jesseward** [comment]
hey @mitsha-microsoft , thanks for the pointer re https://github.com/Azure/aci-deploy/pull/14 . Is there an ETA to cut a new release of the action? Simply pointing the workflow at aci-deploy@master seems to fail as module deps do not appear to be included in master branch.

**Comment by mitsha-microsoft** [comment]
@jesseward yes simply pointing to `aci-deploy@master` won't work since it's not a good advice to point directly to the master branch. Forwarding your issue to @narula0781 and @ashishonce who can release a new version of this action with the updates.

**Pull request closed without merging**
