### PR TITLE
Bugfix/restart policy

### PR DESCRIPTION
**Pull request by alexlydiate**
This fixes the specific issue https://github.com/Azure/aci-deploy/issues/17

### CODE REVIEW

**Comment by alexlydiate** [comment]
This fixes the specific issue https://github.com/Azure/aci-deploy/issues/17

**Review by jahsan1 — APPROVED** [review]
This PR is approved. 

Experiencing the same issue here.

**Comment by kanika1894** [comment]
Hey @alexlydiate, thanks for taking initiative to fix an issue here.
Can you please provide a bit more context, as in what issue were you facing and how are these changes solving the same?
Thanks a lot!

**Comment by alexlydiate** [comment]
Hi @kanika1894 - The issue this fixes is this one: https://github.com/Azure/aci-deploy/issues/17

In short, there is a bug in how it supports the restart policy, which this PR fixes.

**Comment by kanika1894** [comment]
Closing this PR as the changes in this are already covered in https://github.com/Azure/aci-deploy/pull/43.
@alexlydiate I hope it's not a problem.
It just becomes easier to work with one PR will all similar changes :)

**Comment by alexlydiate** [comment]
After 4 months? Cheers, then.

**Pull request closed without merging**
