### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by juliakm**
Addressing issues from https://github.com/Azure/aci-deploy/issues/29

### CODE REVIEW

**Review by kanika1894 — COMMENTED** [review]
Hey @juliakm,
Thanks for picking this up. Quick question, were you able to confirm that it fails if the environment variable is given in single quotes?

**Comment by juliakm** [comment]
@kanika1894 I wasn't able to reproduce the multiline part and have used multiline secrets with this action. In our documentation code samples, we generally don't have quotes (single or double) so I'm wondering if he would have run into problems with both and should have removed them.

**Comment by kanika1894** [comment]
My intent is that whatever we mention in the docs should work and if we are explicitly mentioning about single/double quotes, we should be sure that that's the ideal way.

**Comment by juliakm** [comment]
Sounds good. I've updated the PR.

**Review by kanika1894 — APPROVED** [review]

**Pull request merged**
